server:
  port: 8080
  servlet:
    context-path: /contract

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.71.174:3306/contract?characterEncoding=utf-8&useSSL=false
    username: contract
    password: tS6HWi8k2kjnXxm7
  jpa:
    hibernate:
      ddl-auto: update # 如果数据库不存在就创建
    show-sql: true    # 打印数据库语句

#  jackson:
#    default-property-inclusion: non_null  # 如果为空，不返回

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml